# Generated by Django 5.1.3 on 2025-07-07 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('storage_id', models.IntegerField(primary_key=True, serialize=False)),
                ('storage_name', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
